Ponder.registry((event) => {
    event.create(["embers:alchemy_pedestal", "embers:alchemy_tablet"])
        .scene("kubejs:alchemy", 'Alchemy', "kubejs:alchemy", (scene, utils) => {
            scene.showBasePlate()
            scene.idle(20)
            scene.text(50, 'Alchemy is a complex process')
            scene.idle(60)
            scene.text(50, 'For this, you need to prepare a structure')
            scene.idle(40)

            scene.addKeyframe()
            scene.world.showSection([0, 1, 0, 4, 2, 4], Direction.DOWN)
            scene.idle(40)
            scene.text(50, 'Next, you need to place a Beam Cannon')
            scene.idle(20)
            scene.world.showSection([2, 3, 2], Direction.DOWN)
            scene.idle(10)
            scene.world.showSection([2, 4, 2], Direction.DOWN)
            scene.idle(30)
            scene.text(50, 'Beam Cannon must face Exchange Tablet')
            scene.idle(60)
            scene.text(50, 'And you must give energy to Beam Cannon', [2.5, 4.25, 2.5])
            scene.idle(70)
            scene.rotateCameraY(45)
            scene.idle(30)

            scene.addKeyframe()
            scene.text(50, 'The upper part of it contains materials', [4.5, 2.25, 2.5])
            scene.idle(60)
            scene.text(50, 'And put the aspectus in the lower part', [4.5, 1.5, 2.5])
            scene.idle(60)
            scene.showControls(10, [4.5, 2.5, 2.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.showControls(10, [2.5, 2.5, 4.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.showControls(10, [0.5, 2.5, 2.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.showControls(10, [2.5, 2.5, 0.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.rotateCameraY(45)
            scene.idle(20)
            scene.showControls(10, [2.5, 1.5, 2.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_ingot")
            scene.idle(30)
            scene.text(50, 'After placing the materials')
            scene.idle(60)
            scene.text(50, 'You must guess the ratio of each aspectus from JEI')
            scene.idle(60)
            scene.text(50, 'And put them in the right place')
            scene.idle(20)
            scene.showControls(10, [2.5, 1.5, 0.5], "left")
                .rightClick()
            scene.idle(80)

            scene.addKeyframe()
            scene.text(50, 'After everything is ready, you need to send it a redstone signal', [2.5, 4.25, 2.5])
            scene.idle(60)
            scene.world.showSection([3, 3, 2], Direction.DOWN)
            scene.idle(15)
            scene.showControls(10, [3, 3.5, 2.5], "left")
                .rightClick()
            scene.idle(30)
            scene.text(50, 'Subsequently, the ceremony will begin')
            scene.idle(100)

            scene.addKeyframe()
            scene.text(60, 'After waiting for a period of time, you will receive one of the following two items')
            scene.idle(20)
            scene.rotateCameraY(-45)
            scene.idle(60)
            scene.world.createItemEntity([1.5, 2, 2.5], Direction.DOWN, "embers:alchemical_waste")
            scene.world.createItemEntity([3.5, 2, 2.5], Direction.DOWN, "embers:winding_gears")
            scene.idle(40)
            scene.text(50, 'The waste', [1.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, 'And the product', [3.5, 1.5, 2.5])
            scene.idle(70)
            scene.text(50, 'If you get the waste', [1.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, 'You can only guess their ratio again', [1.5, 1.5, 2.5])
            scene.idle(70)
            scene.text(50, 'If you get the product', [3.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, 'Please note their ratio', [3.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, 'The equipment in this saves will not change', [3.5, 1.5, 2.5])
            scene.idle(60)
        })
})