Ponder.registry((event) => {
    event.create(["embers:alchemy_pedestal", "embers:alchemy_tablet"])
        .scene("kubejs:alchemy", '炼金', "kubejs:alchemy", (scene, utils) => {
            scene.showBasePlate()
            scene.idle(20)
            scene.text(50, '炼金是一个复杂的过程')
            scene.idle(60)
            scene.text(50, '为此，你需要准备一个结构')
            scene.idle(40)

            scene.addKeyframe()
            scene.world.showSection([0, 1, 0, 4, 2, 4], Direction.DOWN)
            scene.idle(40)
            scene.text(50, '下一步，放置一个Beam Cannon上去')
            scene.idle(20)
            scene.world.showSection([2, 3, 2], Direction.DOWN)
            scene.idle(10)
            scene.world.showSection([2, 4, 2], Direction.DOWN)
            scene.idle(30)
            scene.text(50, 'Beam Cannon必须朝向Exchange Tablet')
            scene.idle(60)
            scene.text(50, '并且你需要给Beam Cannon提供余烬能量', [2.5, 4.25, 2.5])
            scene.idle(70)
            scene.rotateCameraY(45)
            scene.idle(30)

            scene.addKeyframe()
            scene.text(50, '上半部分放入炼金的原料', [4.5, 2.25, 2.5])
            scene.idle(60)
            scene.text(50, '下半部分放入元素的标志物', [4.5, 1.5, 2.5])
            scene.idle(60)
            scene.showControls(10, [4.5, 2.5, 2.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.showControls(10, [2.5, 2.5, 4.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.showControls(10, [0.5, 2.5, 2.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.showControls(10, [2.5, 2.5, 0.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_plate")
            scene.idle(10)
            scene.rotateCameraY(45)
            scene.idle(20)
            scene.showControls(10, [2.5, 1.5, 2.5], "left")
                .rightClick()
                .withItem("embers:dawnstone_ingot")
            scene.idle(30)
            scene.text(50, '放置材料之后')
            scene.idle(60)
            scene.text(50, '你需要从JEI查阅元素象征的种类并猜哪个材料对应哪个元素')
            scene.idle(60)
            scene.text(50, '然后放到正确的位置上')
            scene.idle(20)
            scene.showControls(10, [2.5, 1.5, 0.5], "left")
                .rightClick()
            scene.idle(80)

            scene.addKeyframe()
            scene.text(50, '万事俱备后，给它通入红石信号', [2.5, 4.25, 2.5])
            scene.idle(60)
            scene.world.showSection([3, 3, 2], Direction.DOWN)
            scene.idle(15)
            scene.showControls(10, [3, 3.5, 2.5], "left")
                .rightClick()
            scene.idle(30)
            scene.text(50, '很快，仪式就开始了')
            scene.idle(100)

            scene.addKeyframe()
            scene.text(60, '一会后，你会得到两种东西之一')
            scene.idle(20)
            scene.rotateCameraY(-45)
            scene.idle(60)
            scene.world.createItemEntity([1.5, 2, 2.5], Direction.DOWN, "embers:alchemical_waste")
            scene.world.createItemEntity([3.5, 2, 2.5], Direction.DOWN, "embers:winding_gears")
            scene.idle(40)
            scene.text(50, '失败物', [1.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, '和成品', [3.5, 1.5, 2.5])
            scene.idle(70)
            scene.text(50, '如果是失败物', [1.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, '你需要重新猜测各物品所对应的的元素象征', [1.5, 1.5, 2.5])
            scene.idle(70)
            scene.text(50, '如果是成品', [3.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, '请记下配比', [3.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, '同个存档的配比不会改变', [3.5, 1.5, 2.5])
            scene.idle(60)
            scene.text(50, '更多细节请查阅MC百科')
            scene.idle(60)
        })
})