ServerEvents.tags('block', event => {
    //输入输出分开 标准版
    event.add('mm:item_port_output', 'mm:basic_item_port_output')
    event.add('mm:item_port_output', 'mm:advanced_item_port_output')
    event.add('mm:item_port_output', 'mm:elite_item_port_output')
    event.add('mm:item_port_output', 'mm:ultimate_item_port_output')
    event.add('mm:item_port_input', 'mm:basic_item_port_input')
    event.add('mm:item_port_input', 'mm:advanced_item_port_input')
    event.add('mm:item_port_input', 'mm:elite_item_port_input')
    event.add('mm:item_port_input', 'mm:ultimate_item_port_input')

    event.add('mm:fluid_port_output', 'mm:basic_fluid_port_output')
    event.add('mm:fluid_port_output', 'mm:advanced_fluid_port_output')
    event.add('mm:fluid_port_input', 'mm:basic_fluid_port_input')
    event.add('mm:fluid_port_input', 'mm:advanced_fluid_port_input')

    event.add('mm:gas_port_output', 'mm:basic_gas_port_output')
    event.add('mm:gas_port_output', 'mm:advanced_gas_port_output')
    event.add('mm:gas_port_input', 'mm:basic_gas_port_input')
    event.add('mm:gas_port_input', 'mm:advanced_gas_port_input')

    event.add('mm:energy_port_output', 'mm:basic_energy_port_output')
    event.add('mm:energy_port_output', 'mm:advanced_energy_port_output')
    event.add('mm:energy_port_output', 'mm:elite_energy_port_output')
    event.add('mm:energy_port_output', 'mm:ultimate_energy_port_output')
    event.add('mm:energy_port_input', 'mm:basic_energy_port_input')
    event.add('mm:energy_port_input', 'mm:advanced_energy_port_input')
    event.add('mm:energy_port_input', 'mm:elite_energy_port_input')
    event.add('mm:energy_port_input', 'mm:ultimate_energy_port_input')

    //输入输出结合
    event.add('mm:item_port', 'mm:basic_item_port_output')
    event.add('mm:item_port', 'mm:advanced_item_port_output')
    event.add('mm:item_port', 'mm:elite_item_port_output')
    event.add('mm:item_port', 'mm:ultimate_item_port_output')
    event.add('mm:item_port', 'mm:basic_item_port_input')
    event.add('mm:item_port', 'mm:advanced_item_port_input')
    event.add('mm:item_port', 'mm:elite_item_port_input')
    event.add('mm:item_port', 'mm:ultimate_item_port_input')

    //流体气体结合
    event.add('mm:fluid_gas_port_output', 'mm:basic_fluid_port_output')
    event.add('mm:fluid_gas_port_output', 'mm:advanced_fluid_port_output')
    event.add('mm:fluid_gas_port_input', 'mm:basic_fluid_port_input')
    event.add('mm:fluid_gas_port_input', 'mm:advanced_fluid_port_input')
    event.add('mm:fluid_gas_port_output', 'mm:basic_gas_port_output')
    event.add('mm:fluid_gas_port_output', 'mm:advanced_gas_port_output')
    event.add('mm:fluid_gas_port_input', 'mm:basic_gas_port_input')
    event.add('mm:fluid_gas_port_input', 'mm:advanced_gas_port_input')

    //所有口结合
    event.add('mm:port', 'mm:basic_item_port_output')
    event.add('mm:port', 'mm:advanced_item_port_output')
    event.add('mm:port', 'mm:elite_item_port_output')
    event.add('mm:port', 'mm:ultimate_item_port_output')
    event.add('mm:port', 'mm:basic_item_port_input')
    event.add('mm:port', 'mm:advanced_item_port_input')
    event.add('mm:port', 'mm:elite_item_port_input')
    event.add('mm:port', 'mm:ultimate_item_port_input')

    event.add('mm:port', 'mm:basic_fluid_port_output')
    event.add('mm:port', 'mm:advanced_fluid_port_output')
    event.add('mm:port', 'mm:basic_fluid_port_input')
    event.add('mm:port', 'mm:advanced_fluid_port_input')

    event.add('mm:port', 'mm:basic_gas_port_output')
    event.add('mm:port', 'mm:advanced_gas_port_output')
    event.add('mm:port', 'mm:basic_gas_port_input')
    event.add('mm:port', 'mm:advanced_gas_port_input')

    event.add('mm:port', 'mm:basic_energy_port_output')
    event.add('mm:port', 'mm:advanced_energy_port_output')
    event.add('mm:port', 'mm:elite_energy_port_output')
    event.add('mm:port', 'mm:ultimate_energy_port_output')
    event.add('mm:port', 'mm:basic_energy_port_input')
    event.add('mm:port', 'mm:advanced_energy_port_input')
    event.add('mm:port', 'mm:elite_energy_port_input')
    event.add('mm:port', 'mm:ultimate_energy_port_input')
})